### ISSUE TITLE
HTML Encoding

### ISSUE THREAD

**Issue by dmckminard** [Butzlabben/upnp.dart#2]
Hello !

I had some trouble using the V1 of the Package by the other developer but as you know, it is not responding anymore.
I discovered with surprise your fork, what a good idea!

I still have a problem though:
I want to communicate in UPnP with audio devices for content distribution. But the package seems to send data in HTML, and some UPnP methods seem to conflict with each other (because they are themselves encoded in HTML).
This problem has been reported on the old package by other users: https://github.com/SpinlockLabs/upnp.dart/issues/5

The alternative to this is to encode the requests in HTML Escape. This solves the problem but creates other problems, because as the message is encoded, it becomes unreadable by third party apps (BubbleUPnP, mConnect...).

Do you have a solution to this? I can of course help you as I can to complete this solution!

**Comment by daniel-naegele** [comment]
> The alternative to this is to encode the requests in HTML Escape. This solves the problem but creates other problems, because as the message is encoded, it becomes unreadable by third party apps (BubbleUPnP, mConnect...).

> Do you have a solution to this?

Unfortunately not right now. Do you have a code sample to reproduce this bug? Could you maybe elaborate a bit more on this issue with examples? Shouldn't properly decoding/unescaping html be the job of the third party apps? 

BTW: Maybe also take a look at https://github.com/peterscodee/audio_cast and https://github.com/peterscodee/audio_cast/blob/50ee9225e65909f1db766a325cecaf6f8087ba27/lib/src/adapter/upnp_adapter.dart#L140

**Comment by dmckminard** [comment]
Thanks but the link sent corresponds to the solution we currently have but it has problems.
Third party applications don't do this decoding role (BubbleUPnP, mConnect...) because data from "classic" UPnP uploads is done unencrypted.
Wouldn't there be a way to work from the source with the flutter package?

**Comment by daniel-naegele** [comment]
As far as I can tell, the  current implementation with the escaping/encoding of characters such as `&`, `<`, `>`, `'` and `"` is in accordance with with the current [UPnP specification](https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf), see Section 3.2.4, Page 83.

What are your suggestions on how to change/fix the code?
