### ISSUE TITLE
More points on pub deb

### ISSUE THREAD

**Issue by guyluz11** [Butzlabben/upnp.dart#3]
It looks like we can have more points in [pub deb](https://pub.dev/packages/upnp2/score) by updating our packages 

![image](https://user-images.githubusercontent.com/9304740/181213306-5bff64db-aca1-4b7c-b52b-190ca64b67ab.png)

**Comment by daniel-naegele** [comment]
Thanks for this issue. If you want, you can also open a pull request with the needed changes.

**Comment by daniel-naegele** [comment]
I guess we should be good now :)

![](https://i.naegele.dev/U5J3)
