### ISSUE TITLE
`reusePort` not supported for Windows.Dart

### ISSUE THREAD

**Issue by lorenzovianello-vivaldigroup** [Butzlabben/upnp.dart#4]
Hello, 
i've been using upnp (v.1) package for a while then it beacame unsupported so i stopped using it.
Unfortunately, you're giving back the same old error.
Using package ***IN A PURE DART  (NON FLUTTER)*** project, it's impossibile to discover any device or client due to the following error.

```console
Dart Socket ERROR: ../../runtime/bin/socket_win.cc:194: `reusePort` not supported for Windows.Dart Socket ERROR: ../../runtime/bin/socket_win.cc:194: `reusePort` not supported for Windows.Dart Socket ERROR: 
../../runtime/bin/socket_win.cc:194: `reusePort` not supported for Windows.
```

Can this be finally fixed?

**Comment by daniel-naegele** [comment]
This should be fixed now in version 3.0.8
