### ISSUE TITLE
Upnp2 not discover router every time.

### ISSUE THREAD

**Issue by kostadin24** [Butzlabben/upnp.dart#6]
Most of the time plugin discover router. But not always.
Tried rebooting mobile - didn't help. After rebooting router it started working again.
May be something in discovery process create mess and router become not responsive on UpnP

**Comment by daniel-naegele** [comment]
Mhh, could you provide a reproducible minimal example? With maybe mocking a network router? Which OS are you running the code on?

**Comment by kostadin24** [comment]
Sorry for delayed answer. With version 3.0.10 I always see router on my Android 13 device :)
