### ISSUE TITLE
upnp not work  iOS 16

### ISSUE THREAD

**Issue by Silverviql** [Butzlabben/upnp.dart#7]
After updating the phone to the firmware version ios 16 stopped working  route to host.

On 12 and 15 versions of ios everything works.

 Unhandled Exception: SocketException: Send failed (OS Error: No route to host, errno = 65), address = 0.0.0.0, port = 1900
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1213:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2460:15)
#2      DeviceDiscoverer.search (package:upnp2/src/discovery.dart:155:16)
#3      DeviceDiscoverer.quickDiscoverClients (package:upnp2/src/discovery.dart:195:7)
<asynchronous suspension>

Any ideas how to fix this?

**Comment by daniel-naegele** [comment]
Do you have anymore details (e.g. Flutter Version, Package Version, Real Device/Emulator) on that issue? And could you provide a minimal sample for reproducing this issue

**Comment by Silverviql** [comment]
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

package verison   upnp2: ^3.0.10

Real Device iphone 12 ios 16.1.1

```
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:upnp2/upnp.dart' as upnp;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  /// static method to discover Samsung Smart TVs in the network using the UPNP protocol
  Future discover() async {
    var completer = Completer();

    final client = upnp.DeviceDiscoverer();

    final List tvs = [];

    await client.start(ipv6: false);

    client.quickDiscoverClients().listen((client) async {
      RegExp re = RegExp(r'^.*?Samsung.+UPnP.+SDK\/1\.0$');

      //ignore other devices
      if (!re.hasMatch(client.server!)) {
        return;
      }
      try {
        final device = await client.getDevice();

        Uri location = Uri.parse(client.location!);

        final deviceExists = tvs.firstWhere((tv) => tv?.host == location.host, orElse: () => null);

        if (deviceExists == null) {
          if (kDebugMode) {
            print("Found ${device?.friendlyName} on IP ${location.host}");
          }
        }
      } catch (e, stack) {
        if (kDebugMode) {
          print("ERROR: $e - ${client.location}");
          print(stack);
        }
      }
    }).onDone(() {
      if (tvs.isEmpty) {
        completer.completeError("No Samsung TVs found. Make sure the UPNP protocol is enabled in your network.");
      } else {
        completer.complete(tvs);
      }
    });

    return completer.future;
  }


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(

        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: discover,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by Silverviql** [comment]
I was able to solve this issue, requested access to multicast network
and according to the instructions for configured, apparently for ios16 the requirements for access to the multicast network have become stricter.
I am attaching the links that I used to set up:
[access request](https://developer.apple.com/contact/request/networking-multicast)
[xcode](https://linuxtut.com/en/e0a603221def205b71ea/)
[settings](https://developer.apple.com/forums/thread/663271)
[description](https://developer.apple.com/news/?id=0oi77447)

I recommend checking if this is the case, then describe this case in the README
