### ISSUE TITLE
Get in touch

### ISSUE THREAD

**Issue by guyluz11** [Butzlabben/upnp.dart#9]
Hi man how are you doing

I am starting to use your package (even upvote in pub.dev 😉) and I would love to talk with you and understand more about this package.

I am creating a smart home open-source organization named [CyBear Jinni](https://cybearjinni.com) written in flutter and dart native.
Until now I didn't add configuration (directly) for any UPnP devices.
Just bought one and saw in the examples interaction with [Wemo](https://github.com/CyBear-Jinni/cbj_integrations_controller/issues/41) and Chromecast.

I would be happy to talk to you and understand more about if you have knowledge about that stuff (like Chromecast and Wemo)

You can find me in the discord server of CyBear Jinni 

<a href="https://discord.gg/mUXfwUY">
<img align="left" alt="Discord" width="45px" src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" /></a>

**Comment by daniel-naegele** [comment]
That sounds great, I will add you on discord.

**Comment by guyluz11** [comment]
Cool :D
